name: firebase_storage_service
description: Wrapper for Firebase Storage
version: 0.6.0
homepage: https://twitter.com/hikeland
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_storage: ^11.0.2
  flutter_riverpod: ^2.3.6 
  riverpod_annotation: ^2.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.1
  flutter_lints: ^2.0.2  
  riverpod_generator: ^2.2.4 

flutter:



#  